# Generated by Django 2.1.3 on 2018-11-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Profile',
            new_name='profile',
        ),
    ]
