# Generated by Django 2.1.3 on 2018-11-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181118_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
