# Generated by Django 2.1.3 on 2018-11-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('private', models.BooleanField(default=True)),
                ('git_repo', models.URLField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('main_img', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('img_1', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
