# Generated by Django 2.1.3 on 2018-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
