# Generated by Django 2.1.3 on 2018-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181116_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
