# Generated by Django 2.1.3 on 2018-11-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_eduction_experience_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eduction',
            new_name='Education',
        ),
    ]
