# Generated by Django 2.1.3 on 2018-11-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181116_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
