# Generated by Django 2.1.3 on 2018-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_experience_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
