# Generated by Django 2.1.3 on 2018-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20181118_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='learning',
            field=models.BooleanField(default=False),
        ),
    ]
