# Generated by Django 2.1.3 on 2018-12-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20181129_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
    ]
